services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-root}
    volumes:
      - ./climbup-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - ./climbup-redis-data:/data
    command: redis-server --appendonly yes

  server:
    image: ${DOCKER_USERNAME}/climbup-server:dev-latest
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB:-db}
      - DB_USERNAME=${POSTGRES_USER:-root}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OAUTH_AUTHORIZED_REDIRECT_URIS=${OAUTH_AUTHORIZED_REDIRECT_URIS:-http://localhost:5173/oauth2/redirect,https://holdy.kr/oauth2/redirect}
      - OAUTH_DEFAULT_REDIRECT_URI=${OAUTH_DEFAULT_REDIRECT_URI:-http://localhost:5173/oauth2/redirect}
      - DISCORD_ENABLED=${DISCORD_ENABLED:-true}
      - DISCORD_ERROR_WEBHOOK_URL=${DISCORD_DEV_ERROR_WEBHOOK_URL}
      - DISCORD_NOTIFICATION_WEBHOOK_URL=${DISCORD_DEV_NOTIFICATION_WEBHOOK_URL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE_ACTIVE}
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped