services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-db}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_USER=${POSTGRES_USER:-root}
    volumes:
      - ./climbup-db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: ${DOCKER_USERNAME}/climbup-server:latest
    environment:
      - DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB:-db}
      - DB_USERNAME=${POSTGRES_USER:-root}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - APP_OAUTH2_AUTHORIZED_REDIRECT_URI=https://holdy.kr/oauth2/redirect
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped