spring:
  application:
    name: climbup-server

  profiles:
    active: ${SPRING_PROFILE_ACTIVE}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
      file-size-threshold: 2KB
      enabled: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/climbup_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      max-lifetime: 1800000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    validate-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



server:
  forward-headers-strategy: native
  port: 9090
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

jwt:
  secret: ${JWT_SECRET_KEY}
#  access-token-validity-in-seconds: 3600  # 1시간
  access-token-validity-in-seconds: 86400  # 24시간
  refresh-token-validity-in-seconds: 604800  # 7일

app:
  oauth2:
    authorized-redirect-uris: ${OAUTH_AUTHORIZED_REDIRECT_URIS}
    default-redirect-uri: ${OAUTH_DEFAULT_REDIRECT_URI}

# logging:
#   level:
#     root: INFO
#     com.climbup.climbup: DEBUG
#     org.springframework.security: DEBUG
#     org.springframework.web.servlet.resource: WARN
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: WARN
#     org.apache.catalina.core: WARN
#     org.springframework.web.servlet.PageNotFound: WARN

# 운영
logging:
  level:
    root: INFO
    com.climbup.climbup: INFO
    org.springframework.security: WARN
    org.springframework.web.servlet.resource: ERROR
    org.hibernate.SQL: WARN

auth:
  nickname:
    max-retries: 50

ncp:
  storage:
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    region: kr-standard
    endpoint: https://kr.object.ncloudstorage.com
    bucket-name: holdy
    base-url: https://kr.object.ncloudstorage.com/holdy

discord:
  webhook:
    error-url: ${DISCORD_ERROR_WEBHOOK_URL}
    notification-url: ${DISCORD_NOTIFICATION_WEBHOOK_URL}
  enabled: ${DISCORD_ENABLED}