spring:
  application:
    name: climbup-server

  profiles:
    active: ${SPRING_PROFILE_ACTIVE}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/climbup_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    validate-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  forward-headers-strategy: native
  port: 9090
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity-in-seconds: 3600  # 1시간
  refresh-token-validity-in-seconds: 604800  # 7일

app:
  oauth2:
    authorized-redirect-uris: ${OAUTH_AUTHORIZED_REDIRECT_URIS}
    default-redirect-uri: ${OAUTH_DEFAULT_REDIRECT_URI}

discord:
  webhook:
    error-url: ${DISCORD_ERROR_WEBHOOK_URL}
    notification-url: ${DISCORD_NOTIFICATION_WEBHOOK_URL}
  enabled: ${DISCORD_ENABLED}

logging:
  level:
    com.climbup.climbup: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.springframework.web: ${WEB_LOG_LEVEL:WARN}
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

auth:
  nickname:
    max-retries: 50