spring:
  application:
    name: climbup-server

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/climbup_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  forward-headers-strategy: native

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
